// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package zabbix

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "zabbix", asset.ModuleFieldsPri, AssetZabbix); err != nil {
		panic(err)
	}
}

// AssetZabbix returns asset data.
// This is the base64 encoded gzipped contents of module/zabbix.
func AssetZabbix() string {
	return "eJzsWM2O4zYMvs9TEHvaAt2gvWaBAkW7RQfYFj0UPfSykG3GIUYWXYn2xH36QrI9k8RyvE483Qw2PgwylkV+H38kku/gAZs1/KuShHZ3AEKicQ1v2hdv7gAydKmlUojNGn64AwD4OyxCwVml8Q5gQ6gztw5r78CoAvck+keaEteQW67K7k1Eqn9+CZIAdyVbwQySBmSLnbBnhf7ZV7qveEtO2DZP72PaTyA4gaKj3SmADWl0KHs7jyEdwGInBwtjuCaw+edXdhLEAm8CMhIsgobV0bcxRBOonpEJ7mKLRaWFPo1J3pf+gM0j2yz6Ta9k/JsJIxwY4pj3Mwb/9xUz/IscJRqDoyJMexwhiFw0viIcJ/R+JCc+soLOVvIg0N77fy2C23KlM0gQlIBG5XeaocFRY4FGgAwoa1Vz7K/TFp+29ril+72qLDWlynNe2k5PhtnX8R6wKKUB2nSWUhbBsBmE6stT99joeGu7TbPJ55G+90Tvf46HYSTZRo37crwnOfRJFZw2nlSp5vRhIbP9XhUJWh8tDlM2mQNHJkX4UHK6BeEQRAWHJHncooFa6QrhUTlIWWtMBYdGeEtGMEcLpbLyzYhL4tF+CQOjDPcshEPuZxlm/ncwmf+Ro4CC0mJKDlsyA4kdMWIDQmNO8CtOVHF8RZ5L4yPnwEY3K/jO56ZhAVUr0irRg9S0+E9FFrM1bJR2GMXnuLJpPOjPis1nfB/C+eHEksmXgYo1WpImCjZp5JjF/2xJrNHIYufU0uhCCK/iLr3A3T/1yd0eRq2WEwAiB+m519dc1REfnOucuaozrhIdT7Lo0kXqe9Wl5URj4V6uk+g1nNFKxE91g254T8yo9hyQqVnX3jImIBVLub9hcFdadI7YxCq/gdCnSnCi8jugtBrtka6rfBjpOg65vLJSaNH+4tR5+nV2H6LyGRm7iP26wyWohrepMt5MoScZqRT9hytR8TP+uqL2T5WfCNZAJFZyXiuVttb/HB/NOVVOR9EXpPxHF5mh4LvW/qtPH9+BZSivvAHr2AxktsxOd2DL1uW989mCxZRrtE0XCGNDhfLTsgju/WVCDsiBOsYg3vX9qg+J8iBWxyCOHzbz26rv25FRD/AAwLdtMzMGf1jDikWTvWAF28q/jcK//KD4Ngq/jcInLH3JKHyRkvQ2KL8Nyq92UJ5yZeLX0iUkAro9aLBhCwpyqtHAlisbB1OQiUI5Z9r1GxkqqmJv1vWZIFQd7wXPAfFjjVblOB9EoXbLWULtpi3xXwAAAP//tg5N8g=="
}
