// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package zabbix

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "zabbix", asset.ModuleFieldsPri, AssetZabbix); err != nil {
		panic(err)
	}
}

// AssetZabbix returns asset data.
// This is the base64 encoded gzipped contents of module/zabbix.
func AssetZabbix() string {
	return "eJzMlE9y8yAMxfc+xRvv8x3Ai2/ZazT+oyRMsKEg0tDTd2JCx3GV2J0uUhZeSH4/ngBpgyPFCh9106hzAbBiTRXKFCgLoCPfOmVZmaHC/wIAXhTpzoPO1jimDk0EHwjbJNqiN13QVAC78cdqFG0w1D1NtrosjpYq7J0J9hoRtrvlJNbo+qA8Gxe/wplXjsByEhepad0p5srGTmnyxBPJ3My0uMv3JpEtMZ15luiDZvUq0abEI8V347pv+QyW8lnbatMeRTvaDHu5AP+z/1n15Lnu7ToZ4OgtKEddhV2tPYlQb4Jr5XOUj2MVlE7kFEcR20Se77eGSScaWM3d/Kr2U60D/ZPLXL7xpBYe251XeKsTLC9cf9J1JjRavi8hlbUH42WX03GQ11KbCLAHZaf1uAGxqgmx8DIfjoY/4DDrxzOXe/8po6u2Vqu2vgzsJ7n6DAAA//+hYruH"
}
