- module: zabbix

  history:
    enabled: true
    # Set custom paths for the history files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

  problems:
    enabled: true
    # Set custom paths for the problems files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

  trends:
    enabled: true
    # Set custom paths for the trends files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:
